#!/usr/bin/env python3
"""Collect every TODO: in the repository into TODO.md.

The house rules turn every unknown detail into `TODO: <specific question>`
where it is found. This sweep gathers them into one list, so an open-ended
piece of work becomes a finite set of questions. A TODO already written as a
question is a worklist item. One that is not is carried through verbatim and
marked, because rewording it here would mean inventing the question.

What it reads: every file git tracks, except TODO.md itself, anything under
.claude/, any *.secrets.md file, binary files, files over 1 MB, and any path
matching an --exclude pattern. A marker written inside backticks, `TODO:`, is
a mention of the convention rather than a TODO, and so is anything inside a
fenced code block in a Markdown file. Both are skipped.

The output carries no date, so running the sweep twice on the same tree
writes the same bytes, and a stale TODO.md shows up as a diff.

It never overwrites a TODO.md it did not write. A hand-written TODO.md is
refused rather than replaced; choose another path with --out.

Standard library only. Python 3.8 or later.

Usage:
    python3 .claude/kit/todo_sweep.py
    python3 .claude/kit/todo_sweep.py --check            exit 1 when TODO.md is stale
    python3 .claude/kit/todo_sweep.py --out docs/TODO.md
    python3 .claude/kit/todo_sweep.py --exclude 'vendor/*' --exclude 'archive/*'
"""

import argparse
import fnmatch
import os
import re
import subprocess
import sys

MARKER = "Generated by `.claude/kit/todo_sweep.py`"
MAX_BYTES = 1024 * 1024
TODO_RE = re.compile(r"(?<![A-Za-z0-9_`])TODO:\s*(.*)")
FENCE_RE = re.compile(r"^\s*(```|~~~)")
MARKDOWN = (".md", ".markdown", ".mdx")
# Characters that close a comment and are not part of the question.
COMMENT_TAIL = re.compile(r"\s*(\*/|-->|#\})\s*$")


class Item:
    def __init__(self, path, line, text):
        self.path = path
        self.line = line
        self.text = text

    @property
    def is_question(self):
        # A question often asks and then adds a sentence of context ending in
        # a full stop, so the test is whether it asks anything at all.
        return "?" in self.text


def tracked_files(root):
    out = subprocess.run(
        ["git", "-C", root, "ls-files", "-z"],
        check=True,
        stdout=subprocess.PIPE,
    ).stdout
    return sorted(p for p in out.decode("utf-8", "replace").split("\0") if p)


def excluded(path, out_path, patterns):
    if path == out_path:
        return True
    if path.startswith(".claude/") or path.endswith(".secrets.md"):
        return True
    return any(fnmatch.fnmatch(path, pattern) for pattern in patterns)


def read_text(full):
    try:
        if os.path.getsize(full) > MAX_BYTES:
            return None
        with open(full, "rb") as handle:
            data = handle.read()
    except OSError:
        return None
    if b"\0" in data:
        return None
    return data.decode("utf-8", "replace").splitlines()


def continuation(lines, index):
    """The wrapped remainder of a Markdown TODO.

    A question routinely runs across two or three wrapped lines and its
    question mark lands on the last of them. It ends where a Markdown
    paragraph ends: a blank line, a heading, a list item, a quote, a table
    row, a code fence, or the next TODO.
    """
    parts = []
    for line in lines[index + 1:]:
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "-", "*", ">", "|", "```", "~~~")):
            break
        if stripped[0].isdigit() and stripped[1:2] in (".", ")"):
            break
        if TODO_RE.search(line):
            break
        parts.append(stripped)
    return parts


def sweep_file(path, lines):
    items = []
    markdown = path.lower().endswith(MARKDOWN)
    fenced = False
    for index, line in enumerate(lines):
        if markdown and FENCE_RE.match(line):
            fenced = not fenced
            continue
        if fenced:
            continue
        match = TODO_RE.search(line)
        if not match:
            continue
        text = COMMENT_TAIL.sub("", match.group(1)).strip().lstrip("* ")
        if markdown:
            text = " ".join([text] + continuation(lines, index)).strip()
        items.append(Item(path, index + 1, text or "(empty)"))
    return items


def render(items):
    files = sorted({item.path for item in items})
    not_questions = sum(1 for item in items if not item.is_question)
    out = [
        "# TODO",
        "",
        MARKER + " from every `TODO:` in the repository. Never edit it by",
        "hand: answer each question where it is asked, then run the sweep again.",
        "",
    ]
    if not items:
        out += ["No open TODOs.", ""]
        return "\n".join(out)
    summary = "**{} open, in {} {}.**".format(
        len(items), len(files), "file" if len(files) == 1 else "files"
    )
    if not_questions:
        summary += " {} {} not yet written as a question.".format(
            not_questions, "is" if not_questions == 1 else "are"
        )
    out += [summary, ""]
    for path in files:
        out += ["## `{}`".format(path), ""]
        for item in items:
            if item.path != path:
                continue
            flag = "" if item.is_question else " **Not yet a question.**"
            out.append("- Line {}: {}{}".format(item.line, item.text, flag))
        out.append("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description="Collect every TODO: into TODO.md.")
    parser.add_argument("--out", default="TODO.md", help="output path, relative to the repository root")
    parser.add_argument("--exclude", action="append", default=[], help="glob of paths to skip; repeatable")
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 when the output is stale")
    args = parser.parse_args()

    try:
        root = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
        ).stdout.decode().strip()
    except (OSError, subprocess.CalledProcessError):
        sys.exit("todo_sweep: not inside a git repository")

    out_path = os.path.normpath(args.out).replace(os.sep, "/")
    items = []
    for path in tracked_files(root):
        if excluded(path, out_path, args.exclude):
            continue
        lines = read_text(os.path.join(root, path))
        if lines is not None:
            items.extend(sweep_file(path, lines))
    rendered = render(items)

    target = os.path.join(root, out_path)
    current = None
    if os.path.exists(target):
        with open(target, encoding="utf-8") as handle:
            current = handle.read()
        if MARKER not in current:
            sys.exit(
                "todo_sweep: {} exists and was not written by this sweep. "
                "Refusing to overwrite it; choose another path with --out.".format(out_path)
            )

    if args.check:
        if current != rendered:
            sys.exit("todo_sweep: {} is stale. Run the sweep and commit it.".format(out_path))
        print("todo_sweep: {} is current, {} open.".format(out_path, len(items)))
        return

    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print("todo_sweep: wrote {}, {} open.".format(out_path, len(items)))


if __name__ == "__main__":
    main()
